name: Build Halo Fat Jar
on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 17 * * *'
jobs:
  halo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: halo-dev/halo
          path: halo
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: actions/checkout@v3
        with:
          repository: halo-dev/console
          path: console
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install -g pnpm
      - name: copy resources
        run: |
          cd console
          pnpm install
          pnpm build:packages
          pnpm build
          mkdir -p ../halo/src/main/resources/console
          ls -lah 
          cp -r dist/* ../halo/src/main/resources/console
      - name: Read value from Properties-file
        id: property
        uses: christian-draeger/read-properties@1.1.0
        with:
          path: './halo/gradle.properties'
          properties: 'version'
      - name: build
        run: |
          cd halo 
          ./gradlew clean build -x check -x jar
          ls -lah build/libs
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.property.outputs.version }}
          tag_name: ${{ steps.property.outputs.version }}
          token: ${{ secrets.TOKEN }}
          prerelease: true
          files: halo/build/libs/halo-${{ steps.property.outputs.version }}.jar
