name: learn-github-actions
on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 5,17 * * *'
jobs:
  halo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: halo-dev/halo
          path: halo
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - run: |
          cd halo
      - uses: actions/checkout@v3
        with:
          repository: halo-dev/console
          path: console
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install -g pnpm
      - run: |
          cd console
          pnpm install
          pnpm build:packages
          pnpm build
          mkdir ../halo/src/main/resources/console
          cp -r dist/* ../halo/src/main/resources/console
      - run: |
          cd halo 
          ./gradlew clean build -x check -x jar
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: halo/build/libs/halo-*.jar